#!/usr/bin/python3

DOMAIN = "leaptime-manager"
PATH = "/usr/share/locale"

import os
import gettext
import additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=leaptime-manager
Icon=leaptime-manager
Terminal=false
Type=Application
Encoding=UTF-8
Categories=System;Settings;
StartupNotify=false
NotShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/leaptime-manager.desktop", prefix, _("Leaptime Manager"), _("Aiming to be an all-in-one, friendly to new-users, GUI based backup manager for Debian/Ubuntu based systems."), suffix)

prefix = "[Desktop Entry]\n"

suffix = """Exec=leaptime-manager
Icon=leaptime-manager
Terminal=false
Type=Application
Encoding=UTF-8
Categories=System;Settings;
X-KDE-StartupNotify=false
OnlyShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/kde4/leaptime-manager.desktop", prefix, _("Leaptime Manager"), _("Aiming to be an all-in-one, friendly to new-users, GUI based backup manager for Debian/Ubuntu based systems."), suffix, genericName=_("Leaptime Manager"))
