#!/usr/bin/python3

DOMAIN = "leaptime-manager"
PATH = "/usr/share/locale"

import os
import gettext
import additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=leaptime-manager -g
Icon=leaptime-manager
Terminal=false
Type=Application
Encoding=UTF-8
Categories=System;Settings;
StartupNotify=true
"""

additionalfiles.generate(DOMAIN, PATH, "data/applications/leaptime-manager.desktop", prefix, _("LeapTime Manager"), _("Aiming to be an all-in-one, friendly to new-users, GUI based backup manager for Debian/Ubuntu based systems."), suffix)
