# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for all branches
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        language: [ 'python' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive

      # Runs a single command using the runners shell
      - name: update-system
        run: sudo apt-get update -qq
      
      - name: Install Build and Runtime Depends
        run: |
          sudo apt install desktop-file-utils gettext libglib2.0-bin \
          gtk-update-icon-cache meson python3-all pybuild-plugin-pyproject \
          python3-docutils python3-sphinx python3-sphinx-argparse
          sudo apt install gir1.2-gtk-3.0 gir1.2-xapp-1.0 python3-apt \
          python3-aptdaemon.gtk3widgets python3-gi python3-configobj \
          python3-setproctitle python3-tldextract
      
      - name: Build and Test
        run: ./test/test -qq
